/* gernerated by scripts */

#ifndef __REPEATE_DEF_H__
#define __REPEATE_DEF_H__

#define CONCAT(a, b)       a##_##b
#define X_ITEM(x, i)       CONCAT(x, i)
#define X_ITEM_S(x, i, s)  x##_##i##_##s

#define REPEAT_1(m, x) m(x, 1)
#define REPEAT_S_1(m, x, s) m(x, 1, s)
#define REPEAT_2(m, x) REPEAT_1(m, x), m(x, 2)
#define REPEAT_S_2(m, x, s) REPEAT_S_1(m, x, s), m(x, 2, s)
#define REPEAT_3(m, x) REPEAT_2(m, x), m(x, 3)
#define REPEAT_S_3(m, x, s) REPEAT_S_2(m, x, s), m(x, 3, s)
#define REPEAT_4(m, x) REPEAT_3(m, x), m(x, 4)
#define REPEAT_S_4(m, x, s) REPEAT_S_3(m, x, s), m(x, 4, s)
#define REPEAT_5(m, x) REPEAT_4(m, x), m(x, 5)
#define REPEAT_S_5(m, x, s) REPEAT_S_4(m, x, s), m(x, 5, s)
#define REPEAT_6(m, x) REPEAT_5(m, x), m(x, 6)
#define REPEAT_S_6(m, x, s) REPEAT_S_5(m, x, s), m(x, 6, s)
#define REPEAT_7(m, x) REPEAT_6(m, x), m(x, 7)
#define REPEAT_S_7(m, x, s) REPEAT_S_6(m, x, s), m(x, 7, s)
#define REPEAT_8(m, x) REPEAT_7(m, x), m(x, 8)
#define REPEAT_S_8(m, x, s) REPEAT_S_7(m, x, s), m(x, 8, s)
#define REPEAT_9(m, x) REPEAT_8(m, x), m(x, 9)
#define REPEAT_S_9(m, x, s) REPEAT_S_8(m, x, s), m(x, 9, s)
#define REPEAT_10(m, x) REPEAT_9(m, x), m(x, 10)
#define REPEAT_S_10(m, x, s) REPEAT_S_9(m, x, s), m(x, 10, s)
#define REPEAT_11(m, x) REPEAT_10(m, x), m(x, 11)
#define REPEAT_S_11(m, x, s) REPEAT_S_10(m, x, s), m(x, 11, s)
#define REPEAT_12(m, x) REPEAT_11(m, x), m(x, 12)
#define REPEAT_S_12(m, x, s) REPEAT_S_11(m, x, s), m(x, 12, s)
#define REPEAT_13(m, x) REPEAT_12(m, x), m(x, 13)
#define REPEAT_S_13(m, x, s) REPEAT_S_12(m, x, s), m(x, 13, s)
#define REPEAT_14(m, x) REPEAT_13(m, x), m(x, 14)
#define REPEAT_S_14(m, x, s) REPEAT_S_13(m, x, s), m(x, 14, s)
#define REPEAT_15(m, x) REPEAT_14(m, x), m(x, 15)
#define REPEAT_S_15(m, x, s) REPEAT_S_14(m, x, s), m(x, 15, s)
#define REPEAT_16(m, x) REPEAT_15(m, x), m(x, 16)
#define REPEAT_S_16(m, x, s) REPEAT_S_15(m, x, s), m(x, 16, s)
#define REPEAT_17(m, x) REPEAT_16(m, x), m(x, 17)
#define REPEAT_S_17(m, x, s) REPEAT_S_16(m, x, s), m(x, 17, s)
#define REPEAT_18(m, x) REPEAT_17(m, x), m(x, 18)
#define REPEAT_S_18(m, x, s) REPEAT_S_17(m, x, s), m(x, 18, s)
#define REPEAT_19(m, x) REPEAT_18(m, x), m(x, 19)
#define REPEAT_S_19(m, x, s) REPEAT_S_18(m, x, s), m(x, 19, s)
#define REPEAT_20(m, x) REPEAT_19(m, x), m(x, 20)
#define REPEAT_S_20(m, x, s) REPEAT_S_19(m, x, s), m(x, 20, s)
#define REPEAT_21(m, x) REPEAT_20(m, x), m(x, 21)
#define REPEAT_S_21(m, x, s) REPEAT_S_20(m, x, s), m(x, 21, s)
#define REPEAT_22(m, x) REPEAT_21(m, x), m(x, 22)
#define REPEAT_S_22(m, x, s) REPEAT_S_21(m, x, s), m(x, 22, s)
#define REPEAT_23(m, x) REPEAT_22(m, x), m(x, 23)
#define REPEAT_S_23(m, x, s) REPEAT_S_22(m, x, s), m(x, 23, s)
#define REPEAT_24(m, x) REPEAT_23(m, x), m(x, 24)
#define REPEAT_S_24(m, x, s) REPEAT_S_23(m, x, s), m(x, 24, s)
#define REPEAT_25(m, x) REPEAT_24(m, x), m(x, 25)
#define REPEAT_S_25(m, x, s) REPEAT_S_24(m, x, s), m(x, 25, s)
#define REPEAT_26(m, x) REPEAT_25(m, x), m(x, 26)
#define REPEAT_S_26(m, x, s) REPEAT_S_25(m, x, s), m(x, 26, s)
#define REPEAT_27(m, x) REPEAT_26(m, x), m(x, 27)
#define REPEAT_S_27(m, x, s) REPEAT_S_26(m, x, s), m(x, 27, s)
#define REPEAT_28(m, x) REPEAT_27(m, x), m(x, 28)
#define REPEAT_S_28(m, x, s) REPEAT_S_27(m, x, s), m(x, 28, s)
#define REPEAT_29(m, x) REPEAT_28(m, x), m(x, 29)
#define REPEAT_S_29(m, x, s) REPEAT_S_28(m, x, s), m(x, 29, s)
#define REPEAT_30(m, x) REPEAT_29(m, x), m(x, 30)
#define REPEAT_S_30(m, x, s) REPEAT_S_29(m, x, s), m(x, 30, s)

#define REPEAT(n, m, x) CONCAT(REPEAT, n)(m, x)
#define REPEAT_S(n, m, x, s) CONCAT(REPEAT_S, n)(m, x, s)

#define GENERATE_ARRAY(x, n)   REPEAT(n, X_ITEM, x)
#define GENERATE_ARRAY_S(x, n, s) REPEAT_S(n, X_ITEM_S, x, s)

#endif // __REPEATE_DEF_H__